name: 'Random RickRoll'
branding:
  icon: 'message-circle'  
  color: 'blue'
description: 'Rick-roll when mutation test score decreases.'
inputs: 
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: false
    default: '${{ github.token }}'
  decreased:
    description: 'Whether mutation score decreased'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Compare scores and RickRoll
      shell: bash
      run: |
        DECREASED="${{ inputs.decreased }}"
        
        echo "  Décru: $DECREASED"
        
        # Comparaison des scores 
        if [ "$DECREASED" = "true" ] || [ "$DECREASED" = "1" ]; then
          echo "Le score de mutation a baissé :("
          echo "Voir les détails : https://user-images.githubusercontent.com/37572049/90699500-0cc3ec00-e2a1-11ea-8d13-989526e86b0e.gif"
          exit 1
        fi